apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "speckle.fullname.preview-service" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "speckle.labels.preview-service" $ | indent 4 }}
spec:
  replicas: {{ .Values.preview_service.replicas }}
  selector:
    matchLabels:
{{ include "speckle.selectorLabels.preview-service" $ | indent 6 }}
  template:
    metadata:
      labels:
{{ include "speckle.labels.preview-service" $ | indent 8 }}
    spec:
      priorityClassName: low-priority

      {{- if .Values.db.useCertificate }}
      volumes:
        - name: postgres-certificate
          configMap:
            name: postgres-certificate
      {{- end }}

      # Should be > preview generation time ( 1 hour for good measure )
      terminationGracePeriodSeconds: 3600

      containers:
      - name: main
        image: speckle/speckle-preview-service:{{ .Values.docker_image_tag }}

        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 60
          exec:
            command:
              - node
              - -e
              - process.exit(Date.now() - require('fs').readFileSync('/tmp/last_successful_query', 'utf8') > 3600 * 1000)

        resources:
          requests:
            cpu: {{ .Values.preview_service.requests.cpu }}
            memory: {{ .Values.preview_service.requests.memory }}
          limits:
            cpu: {{ .Values.preview_service.limits.cpu }}
            memory: {{ .Values.preview_service.limits.memory }}

        {{- if .Values.db.useCertificate }}
        volumeMounts:
          - name: postgres-certificate
            mountPath: /postgres-certificate
        {{- end }}

        env:
          - name: PG_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: postgres_url

          - name: DEBUG
            value: "preview-service:*"

          {{- if .Values.db.useCertificate }}
          - name: NODE_EXTRA_CA_CERTS
            value: "/postgres-certificate/ca-certificate.crt"
          {{- end }}

