apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "speckle.fullname.frontend" $ }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "speckle.labels.frontend" $ | indent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
{{ include "speckle.selectorLabels.frontend" $ | indent 6 }}
  template:
    metadata:
      labels:
{{ include "speckle.labels.frontend" $ | indent 8 }}
    spec:
      priorityClassName: high-priority

      containers:
      - name: main
        image: speckle/speckle-frontend:{{ .Values.docker_image_tag }}
        resources:
          requests:
            cpu: {{ .Values.frontend.requests.cpu }}
            memory: {{ .Values.frontend.requests.memory }}
          limits:
            cpu: {{ .Values.frontend.limits.cpu }}
            memory: {{ .Values.frontend.limits.memory }}

        # Allow for k8s to remove the pod from the service endpoints to stop receive traffic
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
