{{ if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speckle-server
  namespace: {{ default .Values.namespace .Values.monitoring.namespace }}
  labels:
    app: speckle-server
    release: {{ .Values.monitoring.release }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      project: speckle-server
  endpoints:
  - port: web

{{ end }}
