{{ if .Values.enable_prometheus_monitoring }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speckle-server
  namespace: {{ .Values.namespace }}
  labels:
    app: speckle-server
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
{{ include "speckle.selectorLabels.serviceMonitor" $ | indent 6 }}
  endpoints:
  - port: web

{{ end }}
